#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import sys
from pathlib import Path


GENERATED_BANNER = (
    "# Generated by scripts/sync-claude-to-codex.py from .claude sources.\n"
    "# Do not edit this file directly.\n"
)


def load_json(path: Path) -> dict:
    with path.open() as f:
        return json.load(f)


def write_text(path: Path, content: str, dry_run: bool) -> None:
    current = path.read_text() if path.exists() else None
    if current == content:
        print(f"OK   {path}")
        return

    if dry_run:
        action = "CREATE" if current is None else "UPDATE"
        print(f"{action} {path}")
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    action = "CREATE" if current is None else "UPDATE"
    print(f"{action} {path}")


def remove_path(path: Path, dry_run: bool) -> None:
    if not path.exists():
        return
    if dry_run:
        print(f"DELETE {path}")
        return
    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink()
    print(f"DELETE {path}")


def sync_directory(src: Path, dst: Path, dry_run: bool, delete: bool) -> None:
    dst.mkdir(parents=True, exist_ok=True)

    src_entries = {entry.name: entry for entry in src.iterdir()}
    dst_entries = {entry.name: entry for entry in dst.iterdir()} if dst.exists() else {}

    for name, src_entry in sorted(src_entries.items()):
        dst_entry = dst / name
        if src_entry.is_dir():
            sync_directory(src_entry, dst_entry, dry_run, delete)
            continue

        content = src_entry.read_text()
        write_text(dst_entry, content, dry_run)

    if not delete:
        return

    for name, dst_entry in sorted(dst_entries.items()):
        if name in src_entries:
            continue
        remove_path(dst_entry, dry_run)


def generate_agents_md(claude_md: Path) -> str:
    body = claude_md.read_text().rstrip()
    return (
        "<!-- Generated by scripts/sync-claude-to-codex.py from CLAUDE.md. -->\n\n"
        f"{body}\n"
    )


def shell_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def normalize_hook_command(command: str) -> str:
    if command.startswith(".claude/hooks/"):
        return f'/bin/bash "$(git rev-parse --show-toplevel)/{command}"'
    return command


def generate_hooks_json(settings: dict) -> str:
    hooks = settings.get("hooks", {})
    output: dict[str, dict] = {"hooks": {}}

    for event_name, groups in hooks.items():
        converted_groups = []
        for group in groups:
            converted_group = {"hooks": []}
            if "matcher" in group:
                converted_group["matcher"] = group["matcher"]
            for hook in group.get("hooks", []):
                converted_hook = dict(hook)
                if hook.get("type") == "command" and "command" in hook:
                    converted_hook["command"] = normalize_hook_command(hook["command"])
                converted_group["hooks"].append(converted_hook)
            converted_groups.append(converted_group)
        output["hooks"][event_name] = converted_groups

    return json.dumps(output, ensure_ascii=False, indent=2) + "\n"


def generate_config_toml(settings: dict) -> str:
    lines = [GENERATED_BANNER.rstrip(), ""]

    codex_settings = settings.get("codex", {})
    if codex_settings.get("suppressUnstableFeaturesWarning") is not None:
        value = "true" if codex_settings["suppressUnstableFeaturesWarning"] else "false"
        lines.append(f"suppress_unstable_features_warning = {value}")

    if "askForApproval" in codex_settings:
        lines.append(f"ask_for_approval = {shell_quote(codex_settings['askForApproval'])}")

    if "sandbox" in codex_settings:
        lines.append(f"sandbox = {shell_quote(codex_settings['sandbox'])}")

    if len(lines) > 2:
        lines.append("")

    if settings.get("hooks"):
        lines.extend(
            [
                "[features]",
                "codex_hooks = true",
                "",
            ]
        )

    mcp_servers = settings.get("mcpServers", {})
    for server_name, server in mcp_servers.items():
        lines.append(f"[mcp_servers.{server_name}]")
        if "command" in server:
            lines.append(f"command = {shell_quote(server['command'])}")
        if "args" in server:
            args = ", ".join(shell_quote(arg) for arg in server["args"])
            lines.append(f"args = [{args}]")
        if "cwd" in server:
            lines.append(f"cwd = {shell_quote(server['cwd'])}")
        env = server.get("env", {})
        if env:
            lines.append("")
            lines.append(f"[mcp_servers.{server_name}.env]")
            for key, value in env.items():
                lines.append(f"{key} = {shell_quote(value)}")
        lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def tokenize_rule_prefix(command: str) -> list[str] | None:
    raw = command.strip()
    wildcard = False

    if raw.endswith(":*"):
        raw = raw[:-2].rstrip()
        wildcard = True
    elif raw.endswith(" *"):
        raw = raw[:-2].rstrip()
        wildcard = True
    elif raw.endswith(":"):
        raw = raw[:-1].rstrip()

    unsupported_markers = ["&&", "||", ";", "|", ">", "<", "$(", "`"]
    if any(marker in raw for marker in unsupported_markers):
        return None

    try:
        tokens = shlex.split(raw)
    except ValueError:
        return None

    if not tokens:
        return None

    if "=" in tokens[0] and not tokens[0].startswith(("=", "./", "/")):
        return None

    if wildcard:
        return tokens
    return tokens


def generate_rules(settings_local: dict) -> str:
    permissions = settings_local.get("permissions", {})
    allow_entries = permissions.get("allow", [])

    seen: set[tuple[str, ...]] = set()
    rules: list[list[str]] = []
    skipped: list[str] = []

    for entry in allow_entries:
        if not isinstance(entry, str):
            skipped.append(str(entry))
            continue
        if not entry.startswith("Bash(") or not entry.endswith(")"):
            skipped.append(entry)
            continue

        inner = entry[5:-1]
        pattern = tokenize_rule_prefix(inner)
        if pattern is None:
            skipped.append(entry)
            continue

        key = tuple(pattern)
        if key in seen:
            continue
        seen.add(key)
        rules.append(pattern)

    lines = [GENERATED_BANNER.rstrip(), ""]
    lines.append("# Best-effort migration from .claude/settings.local.json permissions.allow.")
    lines.append("# Only Bash(...) entries that can be represented as Codex prefix rules are included.")
    lines.append("# Imported entries default to prompt because Codex rules govern out-of-sandbox execution.")
    lines.append("")

    if skipped:
        lines.append("# Skipped source entries that need manual review:")
        for entry in skipped:
            lines.append(f"# - {entry}")
        lines.append("")

    auto_allow_patterns = {
        ("cat",),
        ("cargo",),
        ("find",),
        ("git",),
        ("grep",),
        ("head",),
        ("ls",),
        ("pnpm",),
        ("pwd",),
        ("python",),
        ("python3",),
        ("go",),
        ("rg",),
        ("sed",),
        ("tail",),
        ("wc",),
    }

    for pattern in rules:
        rendered_pattern = ", ".join(shell_quote(token) for token in pattern)
        source = " ".join(pattern)
        decision = "allow" if tuple(pattern) in auto_allow_patterns or pattern[:1] == ["gh"] else "prompt"
        lines.extend(
            [
                "prefix_rule(",
                f"    pattern = [{rendered_pattern}],",
                f'    decision = "{decision}",',
                f"    justification = {shell_quote(f'Migrated from .claude permission: {source}')},",
                ")",
                "",
            ]
        )

    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync repo-local Codex configuration from .claude."
    )
    parser.add_argument("--dry-run", action="store_true", help="Show planned changes only")
    parser.add_argument(
        "--delete",
        action="store_true",
        help="Delete generated entries that no longer exist in .claude/skills",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    claude_dir = repo_root / ".claude"
    skills_src = claude_dir / "skills"
    skills_dst = repo_root / ".agents" / "skills"
    claude_md = repo_root / "CLAUDE.md"
    agents_md = repo_root / "AGENTS.md"
    codex_dir = repo_root / ".codex"
    config_toml = codex_dir / "config.toml"
    hooks_json = codex_dir / "hooks.json"
    rules_file = codex_dir / "rules" / "default.rules"

    if not skills_src.exists():
        print(f"Source skills directory not found: {skills_src}", file=sys.stderr)
        return 1

    settings = load_json(claude_dir / "settings.json")
    settings_local = {}
    settings_local_path = claude_dir / "settings.local.json"
    if settings_local_path.exists():
        settings_local = load_json(settings_local_path)

    print("Syncing .claude -> Codex")
    print(f"  repo:    {repo_root}")
    print(f"  dry-run: {args.dry_run}")
    print(f"  delete:  {args.delete}")

    sync_directory(skills_src, skills_dst, args.dry_run, args.delete)
    write_text(agents_md, generate_agents_md(claude_md), args.dry_run)
    write_text(config_toml, generate_config_toml(settings), args.dry_run)
    write_text(hooks_json, generate_hooks_json(settings), args.dry_run)
    if settings_local:
        write_text(rules_file, generate_rules(settings_local), args.dry_run)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
